# Any file that matches one of these fnmatch patterns will be indexed.
patterns:
- Make*
- '*.cpp'
- '*.h'
- '*.js'
- '*.mel'
- '*.php'
- '*.py'
- '*.xml'
- '*.yaml'

# Regular expression to parse a project name from a path.
# /path/to/codesearch.git will be parsed as codesearch.
project_re: .*/(?P<project>[A-Za-z0-9_\-]+)(\.git)?$

# The path on disk to where the codesearch webapp is.
codesearch_path: /path/to/codesearch

# The host that has the MySQL "codesearch" database.
mysql_host: localhost
